#T
cat test.t | ./t
cat test.et | ./t
#S
cat test.s | ./s
cat test.es | ./s

#T2S
#T2J
cat test.s.t | t2mM.pl | mM2j.swl > test.s.t.mM.j
cat test.s.t.mM.j | j2mM.swl | mM2t.pl > test.s.t.mM.j.mM.t
diff test.s.t test.s.t.mM.j.mM.t
#T2M

#S2T
cat test.s | ./s
cat test.s | ./cst in=/dev/stdin > test.s.t
diff test.t test.s.t
---
cat test.es | ./s
cat test.es | ./cst in=/dev/stdin > test.es.et
diff test.et test.es.et

#J2T
cat test.s.t.mM.j | j2mM.swl | mM2t.pl >  test.s.t.mM.j.mM.t
diff test.s.t.mM.j.mM.t test.s.t
#J2M ##1
cat test.s | ./cst in=/dev/stdin | t2mM.pl > test.s.t.mM
mM2j.wl test.s.t.mM > test.s.t.mM.j
j2mM.wl test.s.t.mM.j > test.s.t.mM.j.mM
diff test.s.t.mM test.s.t.mM.j.mM
#J2M ##2
cat test.s | ./cst in=/dev/stdin | t2mM.pl > test.s.t.mM
cat test.s.t.mM | mM2j.swl > test.s.t.mM.j
cat test.s.t.mM.j | j2mM.swl > test.s.t.mM.j.mM
diff test.s.t.mM test.s.t.mM.j.mM

#M2J ##2
cat test.s.t.mM | mM2j.swl > test.s.t.mM.j
cat test.s.t.mM.j | j2mM.swl > test.s.t.mM.j.mM
diff test.s.t.mM test.s.t.mM.j.mM


#M2T
cat test.s.t.mM | ./mM2t.pl > test.s.t.mM.t
diff test.s.t test.s.t.mM.t
