#S
cat test.s | ./s
cat test.es | ./s
#T
cat test.t | ./eet
cat test.et | ./eet


#S2T
cat test.s | ./s
cat test.s | ./cst in=/dev/stdin > test.s.t
diff test.t test.s.t

cat test.es | ./s
cat test.es | ./cst in=/dev/stdin > test.es.et
diff test.et test.es.et

#J2M
cat test.s | ./cst in=/dev/stdin | t2mM.pl > test.s.t.mM
mM2j.wl test.s.t.mM > test.s.t.mM.j
j2mM.wl test.s.t.mM.j > test.s.t.mM.j.mM
diff test.s.t.mM test.s.t.mM.j.mM


#T2S


