#T
cat test.t | ./t
cat test.et | ./t
#S
cat test.s | ./s
cat test.es | ./s


#T2S
#T2J
cat test.s.t | t2mM.pl | mM2j.swl > test.s.t.mM.j
cat test.s.t.mM.j | j2mM.swl | mM2t.pl > test.s.t.mM.j.mM.t
diff test.s.t test.s.t.mM.j.mM.t
#T2M
cat test.s.t | t2mM.pl > test.s.t.mM
cat test.s.t.mM | mM2t.pl > test.s.t.mM.t
diff test.s.t test.s.t.mM.t


#S2T
#S2J
#S2M


#J2T
cat test.s.t.mM.j | j2mM.swl | mM2t.pl > test.s.t.mM.j.mM.t
cat test.s.t.mM.j.mM.t | t2mM.pl | mM2j.swl > test.s.t.mM.j.mM.t.mM.j
diff test.s.t.mM.j test.s.t.mM.j.mM.t.mM.j
#J2S
#J2M
cat test.s.t.mM.j | j2mM.swl > test.s.t.mM.j.mM
cat test.s.t.mM.j.mM | mM2j.swl > test.s.t.mM.j.mM.j
diff test.s.t.mM.j test.s.t.mM.j.mM.j


#M2T
cat test.s.t.mM | ./mM2t.pl > test.s.t.mM.t
cat test.s.t.mM.t | t2mM.pl > test.s.t.mM.t.mM
diff test.s.t.mM test.s.t.mM.t.mM
#M2S
#M2J
cat test.s.t.mM | mM2j.swl > test.s.t.mM.j
cat test.s.t.mM.j | j2mM.swl > test.s.t.mM.j.mM
diff test.s.t.mM test.s.t.mM.j.mM



